Added player name page and removed write test button
philkjacobs/superlatives pull request #39
Opened 2017-11-03 03:28 UTC by mathewantony31

Updated the flow so that you enter your player name in a separate screen before seeing the Host/Join options. I also removed the test button to manually change state to write (it's only host-controlled now!)

2017-11-03 04:07 UTC, philkjacobs requested changes

2017-11-03 04:07 UTC, philkjacobs commented on web/html/index.html
> +        <link type="text/css" rel="stylesheet" href="./style.css">
should be something like web/static/css/style.css

2017-11-03 04:07 UTC, philkjacobs commented on web/js/main.jsx
> +    console.log("ALSO WORKS!")
🤔

2017-11-03 04:07 UTC, philkjacobs commented on web/js/main.jsx
> +      console.log("RECEIVED MESSAGE FROM SERVER")
🤔

2017-11-03 04:07 UTC, philkjacobs commented on web/js/main.jsx
> +    }
spacing was correct before

2017-11-03 04:18 UTC, mathewantony31 commented
@philkjacobs changes made! i'll fix the css in a separate diff

2017-11-05 04:47 UTC, mathewantony31 commented
Finally fixed css issue and added css to the first three pages (Enter name, Menu, waiting room). Right now, it only looks okay if you change your browser to a mobile device.

2017-11-06 05:13 UTC, mathewantony31 commented
Added a "Copy" modal to copy the game ID to clipboard for easy sharing. Also added basic game css to all screens.

2017-11-07 02:44 UTC, philkjacobs approved these changes

2017-11-07 02:45 UTC, merged